services:
  # Backend Service
  - type: web
    name: budget-planner-backend-5od9
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start-render.sh"
    healthCheckPath: "/api/health"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: MONGO_URL
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_NAME
        value: Budget Planner
      - key: ENABLE_EMAIL_SENDING
        value: true
      - key: LOG_LEVEL
        value: INFO
      - key: ACCESS_TOKEN_EXPIRE
        value: 1440
      - key: CORS_ORIGINS
        value: '["https://budget-planner-frontend-fixed.onrender.com"]'

  # Frontend Service
  - type: web
    name: budget-planner-frontend-fixed
    env: static
    plan: free
    region: oregon
    buildCommand: "yarn install && yarn build"
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://budget-planner-backend-5od9.onrender.com
      - key: REACT_APP_ENVIRONMENT
        value: production
      - key: GENERATE_SOURCEMAP
        value: false
    routes:
      - type: rewrite
        source: /api/*
        destination: https://budget-planner-backend-5od9.onrender.com/api/:splat
      - type: rewrite
        source: /*
        destination: /index.html

  # Optional: Background Worker for Email Scheduler
  # Uncomment if you want a dedicated worker for email tasks
  # - type: worker
  #   name: budget-planner-scheduler
  #   env: python
  #   plan: free
  #   buildCommand: "pip install -r requirements.txt"
  #   startCommand: "python -c 'from services.email_scheduler import email_scheduler; email_scheduler.start(); import time; time.sleep(86400)'"
  #   envVars:
  #     - key: ENVIRONMENT
  #       value: production
  #     - key: MONGO_URL
  #       sync: false
  #     - key: SENDGRID_API_KEY
  #       sync: false
  #     - key: JWT_SECRET
  #       sync: false
  #     - key: SENDER_EMAIL
  #       sync: false
